---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./deliveryhero.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./k8tz.yaml
  - ./kubernetes-dashboard.yaml
  - ./rook-ceph.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./nvidia.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./vector.yaml
  - ./vmware-tanzu.yaml
  - ./weave-gitops.yaml
