---
- name: Create disk for ceph
  hosts: all
  become: true

  tasks:
    - name: Fetch the UUID of /dev/sdb
      ansible.builtin.command: blkid -s UUID -o value /dev/sdb
      register: disk_uuid
      changed_when: "disk_uuid.stdout: == ''"

    - name: Unmount /dev/sdb
      ansible.posix.mount:
        path: /mnt/longhorn
        state: unmounted

    - name: Remove line from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "UUID={{ disk_uuid.stdout }} /data ext4 defaults 0 0"
        state: absent

    - name: Remove ext4 filesystem from /dev/sdb
      ansible.builtin.command: wipefs -a /dev/sdb
      become_user: root
      changed_when: false
